# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DATABASE'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DATABASE'] %> 
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
